version: "3.1"
services:
  database:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=splitter"
      - "POSTGRES_USER=benutzer"
      - "POSTGRES_PASSWORD=kennwort"